// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAat0Dhj34712NX_794VOQi0jw6W3J5-jQ',
    appId: '1:1021069332614:web:9dc410a94dd7eb66e50107',
    messagingSenderId: '1021069332614',
    projectId: 'nayanasartistry-e78b0',
    authDomain: 'nayanasartistry-e78b0.firebaseapp.com',
    storageBucket: 'nayanasartistry-e78b0.firebasestorage.app',
    measurementId: 'G-3KK5G4GPMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBFiwitmUJBiwzlL2v0zE-45s1_XSur4',
    appId: '1:1021069332614:android:a2be31565be80cf5e50107',
    messagingSenderId: '1021069332614',
    projectId: 'nayanasartistry-e78b0',
    storageBucket: 'nayanasartistry-e78b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPAEriryfGYoUDJ-viIzHIAHYH2rp99-c',
    appId: '1:1021069332614:ios:02350ff58c6a86ede50107',
    messagingSenderId: '1021069332614',
    projectId: 'nayanasartistry-e78b0',
    storageBucket: 'nayanasartistry-e78b0.firebasestorage.app',
    iosClientId: '1021069332614-c756ecpp6ad6l7jis27adkv7mimgtigp.apps.googleusercontent.com',
    iosBundleId: 'com.example.nayanasartistry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPAEriryfGYoUDJ-viIzHIAHYH2rp99-c',
    appId: '1:1021069332614:ios:02350ff58c6a86ede50107',
    messagingSenderId: '1021069332614',
    projectId: 'nayanasartistry-e78b0',
    storageBucket: 'nayanasartistry-e78b0.firebasestorage.app',
    iosClientId: '1021069332614-c756ecpp6ad6l7jis27adkv7mimgtigp.apps.googleusercontent.com',
    iosBundleId: 'com.example.nayanasartistry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAat0Dhj34712NX_794VOQi0jw6W3J5-jQ',
    appId: '1:1021069332614:web:0cd8108c41cb7c47e50107',
    messagingSenderId: '1021069332614',
    projectId: 'nayanasartistry-e78b0',
    authDomain: 'nayanasartistry-e78b0.firebaseapp.com',
    storageBucket: 'nayanasartistry-e78b0.firebasestorage.app',
    measurementId: 'G-KTHY88P706',
  );
}
